CREATE ROLE "TEMPROLE"  
    IDENTIFIED BY "temprole";
GRANT ALTER ANY INDEX TO "TEMPROLE" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "TEMPROLE" WITH ADMIN OPTION;
GRANT "CONNECT" TO "TEMPROLE" WITH ADMIN OPTION;
GRANT "DBA" TO "TEMPROLE" WITH ADMIN OPTION;
BEGIN
	dbms_resource_manager_privs.grant_switch_consumer_group( 
		grantee_name => 'TEMPROLE',
		consumer_group => 'DEFAULT_CONSUMER_GROUP',
		grant_option => FALSE
	);
END;
