CREATE TABLE "SCOTT"."GRADUATE" (
    "BH"        NUMBER(10) NOT NULL,
    "XM"        VARCHAR2(10) NOT NULL,
    "LB"        VARCHAR2(10) NOT NULL, 
    "YINGYU"    NUMBER(4, 1) NOT NULL,
    "ZHENGZHI"  NUMBER(4, 1) NOT NULL, 
    "ZHUANYE1"  NUMBER(4, 1) NOT NULL,
    "ZHUANYE2"  NUMBER(4, 1) NOT NULL, 
    "ZHUANYE3"  NUMBER(4, 1) NOT NULL)  
TABLESPACE "USERS" 