CREATE TABLE "SCOTT"."STUDENT" (
          "STUDENT_ID"   NUMBER(8)      NOT NULL,
          "NAME"         VARCHAR2(10)   NOT NULL,
          "PROFESSIONAL" VARCHAR2(10)   NOT NULL,
          "BIRTHDAY"     DATE           NOT NULL,
          "DIRECTOR_ID"  NUMBER(6)      NOT NULL, 
    CONSTRAINT "研究生编号主码" PRIMARY KEY("STUDENT_ID") 
    USING INDEX  
    TABLESPACE "USERS",
    CONSTRAINT "导师编号外码" FOREIGN KEY("DIRECTOR_ID") 
    REFERENCES "SCOTT"."DIRECTOR"("DIRECTOR_ID"))  
    TABLESPACE "USERS" 