CREATE USER "GRADUATEUSER"  PROFILE "DEFAULT" 
    IDENTIFIED BY "12345678" DEFAULT TABLESPACE "USERS" 
    TEMPORARY TABLESPACE "TEMP" 
    ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "GRADUATEUSER";
GRANT "CONNECT" TO "GRADUATEUSER";
GRANT "RESOURCE" TO "GRADUATEUSER";