CREATE TABLE "GRADUATEUSER"."DIRECTOR_INFO" ("ID" NUMBER(10) NOT 
    NULL, "NAME" VARCHAR2(10) NOT NULL, "SEX" VARCHAR2(2) NOT 
    NULL, "ZHICHENG" VARCHAR2(20) NOT NULL, "ZHIWU" VARCHAR2(20)
    NOT NULL, "MAJOR" VARCHAR2(40) NOT NULL, 
    CONSTRAINT "µ¼Ê¦±àºÅÖ÷Âë" PRIMARY KEY("ID"))  
    TABLESPACE "USERS" 